application:
  seprator: ","
  output-formats:
    - JSON
  paths:
    input-file-name: /home/nicky/in-csv/test-10000000.csv
    output-file-location: /home/nicky/out
logging:
  level:
    root: INFO
    org.aiolabs.projects.converter: DEBUG
